language: objective-c
osx_image: xcode9.4
xcode_workspace: SmartReceipts.xcworkspace
xcode_scheme: SmartReceipts
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
notifications:
  email:
    recipients:
      - support@smartreceipts.co
    on_success: never # default: change
    on_failure: always # default: always
before_install:
- pod repo update
