language: objective-c
osx_image: xcode11.1
notifications:
  email:
    recipients:
      - ios-build-interest@smartreceipts.co
    on_success: change # default: change
    on_failure: always # default: always

env:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

jobs:
  install:
  - bundle install

  include:
    - stage: test
      name: "Unit Tests"
      if: type = pull_request OR branch ~= release/*
      script:
        - fastlane tests

    - stage: deploy
      name: "Upload to TestFlight"
      if: branch ~= release/*
      script:
        - echo $SECRETS_ENCRYPTION_KEY | base64 --decode | gpg --import
        - fastlane test_flight
