language: objective-c
osx_image: xcode10.2
xcode_workspace: SmartReceipts.xcworkspace
xcode_scheme: SmartReceipts
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
notifications:
  email:
    recipients:
      - ios-build-interest@smartreceipts.co
    on_success: change # default: change
    on_failure: always # default: always
before_install:
- pod repo update
