language: objective-c
osx_image: xcode12.2
notifications:
  email:
    recipients:
      - ios-build-interest@smartreceipts.co
    on_success: change # default: change
    on_failure: always # default: always

env:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

jobs:
  install:
  - bundle install

  include:
    - stage: test
      name: "Unit Tests"
      if: type = pull_request OR branch ~= release/* OR commit_message ~= /(ci_test|deploy|appstore|test_flight)/
      script:
        - fastlane tests

    - stage: deploy
      name: "Upload to TestFlight"
      if: type != pull_request AND (branch ~= release_* OR commit_message ~= /(deploy|appstore|test_flight)/)
      script:
        - echo $SECRETS_ENCRYPTION_KEY | base64 --decode | gpg --import
        - fastlane test_flight
